# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import als_pb2 as als__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in als_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccessLogServiceStub(object):
    """---- service ---------------------------------------------------------------
    Must match envoy.service.accesslog.v3.AccessLogService so envoy can call us.
    gRPC method dispatch is by string path
    ("/envoy.service.accesslog.v3.AccessLogService/StreamAccessLogs"), not by
    proto package, so we declare the service under that fully-qualified name
    by using a wrapper at runtime (see als_server.py register_path).

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAccessLogs = channel.stream_unary(
                '/llmxy.als.AccessLogService/StreamAccessLogs',
                request_serializer=als__pb2.StreamAccessLogsMessage.SerializeToString,
                response_deserializer=als__pb2.StreamAccessLogsResponse.FromString,
                _registered_method=True)


class AccessLogServiceServicer(object):
    """---- service ---------------------------------------------------------------
    Must match envoy.service.accesslog.v3.AccessLogService so envoy can call us.
    gRPC method dispatch is by string path
    ("/envoy.service.accesslog.v3.AccessLogService/StreamAccessLogs"), not by
    proto package, so we declare the service under that fully-qualified name
    by using a wrapper at runtime (see als_server.py register_path).

    """

    def StreamAccessLogs(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessLogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAccessLogs': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamAccessLogs,
                    request_deserializer=als__pb2.StreamAccessLogsMessage.FromString,
                    response_serializer=als__pb2.StreamAccessLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmxy.als.AccessLogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmxy.als.AccessLogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccessLogService(object):
    """---- service ---------------------------------------------------------------
    Must match envoy.service.accesslog.v3.AccessLogService so envoy can call us.
    gRPC method dispatch is by string path
    ("/envoy.service.accesslog.v3.AccessLogService/StreamAccessLogs"), not by
    proto package, so we declare the service under that fully-qualified name
    by using a wrapper at runtime (see als_server.py register_path).

    """

    @staticmethod
    def StreamAccessLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/llmxy.als.AccessLogService/StreamAccessLogs',
            als__pb2.StreamAccessLogsMessage.SerializeToString,
            als__pb2.StreamAccessLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
